# Generated by Django 3.1.4 on 2020-12-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201207_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reccuring_time',
            field=models.CharField(blank=True, choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Yearly')], max_length=1, null=True),
        ),
    ]
